all:
#	gcc -Wall  -c food.c
#	gcc -Wall  -c list.c
#	gcc -Wall  -c resepi.c
#	gcc -Wall main.c food.o list.o resepi.o -o mealplaner.exe
	gcc `pkg-config --cflags gtk+-3.0` -o binery/gui gui.c `pkg-config --libs gtk+-3.0`

clean:
#	rm food.o
#	rm list.o
#	rm mealplaner.exe
